service: datetime-api2 
frameworkVersion: "3"
useDotenv: true


provider: 
  name: huawei
  runtime: Node.js18.15
  stage: ${opt:stage, 'qa'}
  credentials: credentials 
  region: af-south-1 

package:
  individually: true
  patterns:
    - index.js
    - package.json
    - '!.github/**'


functions:
  getDateTime2:
    handler: ./index.handler  
    code:
     codeUri: .
    description: Huawei Serverless Cloud Function
    environment:
      variables:
        ENV_FIRST: env1
        ENV_SECOND: env2
    events:
      - http:
          path: datetime
          method: get

plugins:
  - serverless-huawei-functions
